.TH xml2ogdl 1 "2 Sept 2003"
.SH NAME
xml2ogdl \- XML to OGDL converter
.SH SYNOPSIS

\fBxml2ogdl\fP [options] [filename]

.SH DESCRIPTION
\fBxml2ogdl\fP converts XML streams into OGDL, that is printed to the
standard output.

.SH OPTIONS
.TP
\fB-n\fP \fInumber\fP
Number of spaces used for indentation (default 2).

.SH BUGS

.SH AUTHOR
Rolf Veen. See <http://ogdl.org> for more information.

